name:                website
version:             0.1.0.0
github:              "githubuser/website"
copyright:           "2019 Author name here"

description: my website

executables:
  website-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - servant-server
    - servant-blaze
    - blaze-html
    - blaze-markup
    - wai
    - warp
    - http-client
    - time
    - parsec
    - transformers
